name: Deploy app2.py to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy app2.py to EC2
      - name: Deploy app2.py to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_USER: ec2-user
          EC2_IP: 54.226.160.1
        run: |
          # Set up SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

          # Transfer app2.py to the EC2 instance
          scp app2.py $EC2_USER@$EC2_IP:/home/ec2-user/
